//geracao 99 level: 1 fit: 2741.36
 if( landscape[11+ 1 ][11+ 0 ] != 0 ){ if( landscape[11+ 0 ][11+ -1 ] != -10 ){ if( observation.mayMarioJump() ){ action[ Mario.KEY_JUMP ] = true ;
 }else{ if( landscape[11+ 1 ][11+ 1 ] != 20 ){ action[ Mario.KEY_JUMP ] = false ;
 }else{ action[ Mario.KEY_SPEED ] = true ;
 } action[ Mario.KEY_LEFT ] = true ;
 } if( landscape[11+ 0 ][11+ 0 ] != -11 ){ action[ Mario.KEY_LEFT ] = true ;
 } if( observation.isMarioOnGround() ){ action[ Mario.KEY_SPEED ] = false ;
 }else{ action[ Mario.KEY_JUMP ] = true ;
 } if( observation.isMarioOnGround() ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_RIGHT ] = true ;
 }else{ action[ Mario.KEY_LEFT ] = true ;
 } }else{ if( observation.mayMarioJump() ){ action[ Mario.KEY_RIGHT ] = true ;
 }else{ action[ Mario.KEY_DOWN ] = false ;
 } } }else{ if( enemies[11+ -1 ][11+ -1 ] != Sprite.KIND_GREEN_KOOPA_WINGED ){ action[ Mario.KEY_RIGHT ] = false ;
 } } }else{ if( observation.mayMarioJump() ){ action[ Mario.KEY_DOWN ] = true ;
 action[ Mario.KEY_JUMP ] = true ;
 }else{ action[ Mario.KEY_SPEED ] = true ;
 } if( landscape[11+ 0 ][11+ 1 ] != 0 ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_JUMP ] = true ;
 } } if( enemies[11+ 1 ][11+ 0 ] != Sprite.KIND_RED_KOOPA ){ action[ Mario.KEY_SPEED ] = false ;
 if( landscape[11+ 0 ][11+ -1 ] != 0 ){ if( landscape[11+ 1 ][11+ -1 ] != -10 ){ action[ Mario.KEY_DOWN ] = true ;
 } }else{ if( observation.mayMarioJump() ){ action[ Mario.KEY_DOWN ] = false ;
 }else{ action[ Mario.KEY_LEFT ] = false ;
 } } }else{ if( enemies[11+ 1 ][11+ 0 ] != Sprite.KIND_GOOMBA_WINGED ){ if( observation.mayMarioJump() ){ action[ Mario.KEY_DOWN ] = true ;
 }else{ action[ Mario.KEY_JUMP ] = false ;
 } } action[ Mario.KEY_RIGHT ] = true ;
 } if( observation.isMarioOnGround() ){ if( enemies[11+ 0 ][11+ -1 ] != Sprite.KIND_RED_KOOPA_WINGED ){ action[ Mario.KEY_DOWN ] = false ;
 action[ Mario.KEY_SPEED ] = false ;
 }else{ if( enemies[11+ 1 ][11+ 1 ] != Sprite.KIND_GOOMBA ){ action[ Mario.KEY_JUMP ] = true ;
 } } } if( observation.isMarioOnGround() ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_RIGHT ] = false ;
 }else{ action[ Mario.KEY_RIGHT ] = true ;
 } if( landscape[11+ 1 ][11+ 0 ] != -10 ){ action[ Mario.KEY_LEFT ] = true ;
 }else{ action[ Mario.KEY_JUMP ] = true ;
 } } }