//geracao 99 level: 1 fit: 2729.53
 if( observation.mayMarioJump() ){ if( observation.mayMarioJump() ){ action[ Mario.KEY_JUMP ] = false ;
 action[ Mario.KEY_SPEED ] = true ;
 } action[ Mario.KEY_JUMP ] = true ;
 }else{ if( landscape[11+ 1 ][11+ -1 ] != 0 ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_LEFT ] = false ;
 if( observation.isMarioOnGround() ){ if( observation.mayMarioJump() ){ action[ Mario.KEY_LEFT ] = false ;
 } }else{ if( observation.mayMarioJump() ){ action[ Mario.KEY_RIGHT ] = false ;
 } } action[ Mario.KEY_JUMP ] = false ;
 }else{ if( observation.mayMarioJump() ){ if( observation.mayMarioJump() ){ if( observation.isMarioOnGround() ){ if( observation.mayMarioJump() ){ action[ Mario.KEY_DOWN ] = false ;
 }else{ action[ Mario.KEY_JUMP ] = true ;
 } }else{ action[ Mario.KEY_DOWN ] = true ;
 } }else{ if( enemies[11+ -1 ][11+ -1 ] != Sprite.KIND_BULLET_BILL ){ if( landscape[11+ 0 ][11+ -1 ] != 0 ){ action[ Mario.KEY_SPEED ] = false ;
 } }else{ if( enemies[11+ 0 ][11+ 1 ] != Sprite.KIND_RED_KOOPA ){ action[ Mario.KEY_JUMP ] = true ;
 } } } }else{ if( landscape[11+ -1 ][11+ 1 ] != 0 ){ if( landscape[11+ -1 ][11+ 1 ] != 0 ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_SPEED ] = true ;
 } }else{ action[ Mario.KEY_SPEED ] = false ;
 action[ Mario.KEY_RIGHT ] = false ;
 } }else{ if( landscape[11+ -1 ][11+ 1 ] != 16 ){ if( observation.isMarioOnGround() ){ action[ Mario.KEY_JUMP ] = false ;
 } }else{ if( observation.isMarioOnGround() ){ action[ Mario.KEY_LEFT ] = false ;
 }else{ action[ Mario.KEY_RIGHT ] = true ;
 } } } } } }else{ if( observation.isMarioOnGround() ){ action[ Mario.KEY_DOWN ] = false ;
 }else{ action[ Mario.KEY_RIGHT ] = false ;
 action[ Mario.KEY_RIGHT ] = true ;
 } if( landscape[11+ 0 ][11+ -1 ] != -10 ){ if( enemies[11+ 0 ][11+ 0 ] != Sprite.KIND_GOOMBA ){ if( landscape[11+ 1 ][11+ 0 ] != 0 ){ action[ Mario.KEY_RIGHT ] = true ;
 } }else{ if( observation.mayMarioJump() ){ action[ Mario.KEY_RIGHT ] = true ;
 } } } if( observation.isMarioOnGround() ){ if( enemies[11+ 0 ][11+ 0 ] != Sprite.KIND_RED_KOOPA ){ action[ Mario.KEY_JUMP ] = false ;
 }else{ action[ Mario.KEY_JUMP ] = false ;
 } }else{ action[ Mario.KEY_SPEED ] = true ;
 } if( observation.isMarioOnGround() ){ action[ Mario.KEY_SPEED ] = false ;
 action[ Mario.KEY_RIGHT ] = false ;
 } action[ Mario.KEY_LEFT ] = false ;
 } }